version: "3.9"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8010:8010"
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite:///data/restaurants.db

